export const sunatUnitOptions = [
  { value: "NIU", label: "NIU - Unidad" },
  { value: "ZZ", label: "ZZ - Servicio" },
  { value: "KGM", label: "KGM - Kilogramo" },
  { value: "GRM", label: "GRM - Gramo" },
  { value: "LTR", label: "LTR - Litro" },
  { value: "MLT", label: "MLT - Mililitro" },
  { value: "MTR", label: "MTR - Metro" },
  { value: "CMT", label: "CMT - Centimetro" },
  { value: "MTK", label: "MTK - Metro cuadrado" },
  { value: "MTQ", label: "MTQ - Metro cubico" },
  { value: "BX", label: "BX - Caja" },
  { value: "BG", label: "BG - Bolsa" },
  { value: "BO", label: "BO - Botella" },
  { value: "BJ", label: "BJ - Balde" },
  { value: "BLL", label: "BLL - Barril" },
  { value: "CA", label: "CA - Lata" },
  { value: "CY", label: "CY - Cilindro" },
  { value: "DZN", label: "DZN - Docena" },
  { value: "PK", label: "PK - Paquete" },
  { value: "PR", label: "PR - Par" },
  { value: "SET", label: "SET - Juego" },
  { value: "KT", label: "KT - Kit" },
  { value: "TNE", label: "TNE - Tonelada" },
  { value: "GLL", label: "GLL - Galon" },
  { value: "FOT", label: "FOT - Pie" },
  { value: "INH", label: "INH - Pulgada" },
  { value: "YRD", label: "YRD - Yarda" },
  { value: "C62", label: "C62 - Pieza" },
];
